### ISSUE TITLE
Cannot install tensorflow-cpu 1.15 version

### ISSUE THREAD

**Issue by muhamadnss** [AmeyaUpalanchi/streamlit-tensorflow-ml-app#1]
I have an issue while installing requirements needed by using this syntax :
``pip install -r requirements.txt``

And and the error displayed is :
`ERROR: Could not find a version that satisfies the requirement tensorflow-cpu==1.15 (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for tensorflow-cpu==1.15 (from -r requirements.txt (line 2))`

My device is using python 3.9.0

**Comment by AmeyaUpalanchi** [comment]
Please check if you have the latest version of pip installed. You can upgrade pip using the below command.

```
python3 -m pip install --upgrade pip

```

**Comment by AmeyaUpalanchi** [comment]
Downgrading from python 3.9 to 3.6 will work

**Comment by muhamadnss** [comment]
Yep, thank you for your advice
I just downgrade to python 3.8.0 and install tensorflow separately, but still got some error when I execute :
``streamlit run app.py``

** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "c:\users\lenovo t410\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\lenovo t410\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Learn\python\leafDetection-2\streamlit-tensorflow-ml-app\leaf2\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "e:\learn\python\leafdetection-2\streamlit-tensorflow-ml-app\leaf2\lib\site-packages\streamlit\__init__.py", line 95, in <module>
    import numpy as _np
  File "e:\learn\python\leafdetection-2\streamlit-tensorflow-ml-app\leaf2\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "e:\learn\python\leafdetection-2\streamlit-tensorflow-ml-app\leaf2\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('e:\\learn\\python\\leafdetection-2\\streamlit-tensorflow-ml-app\\leaf2\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

are you familiar with this error ?

**Comment by AmeyaUpalanchi** [comment]
Downgrade numpy to V1.18.1

**Comment by muhamadnss** [comment]
Thanks for your great and fast respond, I'll try it immediately

**Comment by muhamadnss** [comment]
Thankfully there is a little progress, I've downgraded python to version 3.6.0 and all the package modules are properly installed, but I'm still having errors

Traceback (most recent call last):
  File "c:\users\lenovo t410\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lenovo t410\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Learn\python\leafDetection-2\streamlit-tensorflow-ml-app\envLeaf\Scripts\streamlit.exe\__main__.py", line 4, in <module>
  File "e:\learn\python\leafdetection-2\streamlit-tensorflow-ml-app\envleaf\lib\site-packages\streamlit\__init__.py", line 103, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "e:\learn\python\leafdetection-2\streamlit-tensorflow-ml-app\envleaf\lib\site-packages\streamlit\delta_generator.py", line 25, in <module>
    from streamlit.proto import BlockPath_pb2
  File "e:\learn\python\leafdetection-2\streamlit-tensorflow-ml-app\envleaf\lib\site-packages\streamlit\proto\BlockPath_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "e:\learn\python\leafdetection-2\streamlit-tensorflow-ml-app\envleaf\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by AmeyaUpalanchi** [comment]
Try using conda env
